qt: Revert "Force TLS1.0+ for SSL connections"
src/qt/magi.cpp: In function 'int qMain(int, char**)':
src/qt/magi.cpp:138:23: error: variable 'QSslConfiguration sslconf' has initializer but incomplete type
  138 |     QSslConfiguration sslconf = QSslConfiguration::defaultConfiguration();
      |                       ^~~~~~~
src/qt/magi.cpp:138:52: error: incomplete type 'QSslConfiguration' used in nested name specifier
  138 |     QSslConfiguration sslconf = QSslConfiguration::defaultConfiguration();
      |                                                    ^~~~~~~~~~~~~~~~~~~~
src/qt/magi.cpp:139:25: error: 'QSsl' has not been declared
  139 |     sslconf.setProtocol(QSsl::TlsV1_0OrLater);
      |                         ^~~~
src/qt/magi.cpp:140:24: error: incomplete type 'QSslConfiguration' used in nested name specifier
  140 |     QSslConfiguration::setDefaultConfiguration(sslconf);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~

qt: Revert "Force TLS1.0+ for SSL connections"
This reverts commit 15e26a6, whose
purpose was to tweak the Qt configuration to force TLS, i.e., to
disable SSLv3, in Qt versions >= 5.5. However, the default behavior
of Qt >= 5.4 is to disable SSLv3 anyway [1], so the configuration
tweak is redundant.

With Qt 5.11.2, the configuration tweak is not only redundant but in
fact provokes a deadlock (bitcoin#14359) due to Qt 5.11.2 being incompatible
with OpenSSL 1.1.1 [2]. Since the deadlock occurs at the early startup
stage of bitcoin-qt, it renders bitcoin-qt entirely non-functional
when compiled against OpenSSL 1.1.1 and Qt 5.11.2 (and possible future
combinations of OpenSSL and Qt versions).

This commit fixes bitcoin#14359 by removing the redundant code.

[1] https://code.qt.io/cgit/qt/qtbase.git/commit/?id=3fd2d9eff8c1f948306ee5fbfe364ccded1c4b84
[2] https://bugreports.qt.io/browse/QTBUG-70956